### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Lotus-Blue** [resistzzz/Prompt4NR#1]
大佬您好，我我刚刚尝试跑这个项目代码，下载的数据集是https://msnews.github.io/ 下的Mind-Small，原数据集中news是tsv尾缀，我使用python处理变成了txt尾缀，然后放在相应目录下跑代码，但是报错：
![1682425877(1)](https://user-images.githubusercontent.com/45590660/234276750-a1ed6ac7-48d2-416f-a54f-5acdfb17859f.png)
想问问ga该如何解决呢，还是我疏忽没认真看论文，数据集还需要进行其他处理呢，非常期待您的答复

**Comment by resistzzz** [comment]
实际上我的.txt文件是处理后用pickle存储成的二进制文件，所以我也是直接用pickle读取出来的，你稍等，我稍后就把我处理好的数据集上传

**Comment by Lotus-Blue** [comment]
> 实际上我的.txt文件是处理后用pickle存储成的二进制文件，所以我也是直接用pickle读取出来的，你稍等，我稍后就把我处理好的数据集上传

好，感谢回复，非常期待您的更新

**Comment by resistzzz** [comment]
感谢你对我科研工作的关注，我已经更新了Readme文件，由于数据集大小，Github上传不了数据集，我已经将预处理好的数据集上传到Google Drive上，后续有任何问题欢迎与我进行交流！
Google Drive链接：https://drive.google.com/drive/folders/1_3ffZvEPKD5deHbTU_mVGp6uEaLhyM7c?usp=sharing

**Comment by Lotus-Blue** [comment]
> 感谢你对我科研工作的关注，我已经更新了Readme文件，由于数据集大小，Github上传不了数据集，我已经将预处理好的数据集上传到Google Drive上，后续有任何问题欢迎与我进行交流！ Google Drive链接：https://drive.google.com/drive/folders/1_3ffZvEPKD5deHbTU_mVGp6uEaLhyM7c?usp=sharing

已收到，非常感谢

**Comment by resistzzz** [comment]
我那个是个处理好的二进制文件，只不过用.txt做后缀罢了，而不是把.tsv转换成文本形式的.txt，你可以直接去读取我处理好的数据就行。

Lotus-Blue ***@***.***> 于2023年4月25日周二 20:32写道：
