### ISSUE TITLE
Some questions about experiment running

### ISSUE THREAD

**Issue by QuXiaolong0812** [resistzzz/Prompt4NR#2]
Hello, dear authors. I would like to say that this is a very interesting job, which attracts me very much. Therefore, I want to reproduce your experimental results. I would like to ask, how long does it take you to run once? Could you give me a brief introduction to the running time of each template. Thanks for your reply!

**Comment by Lotus-Blue** [comment]
兄弟跑成功了吗，我这边似乎有点棘手，不是提示FileNotFoundError: [Errno 2] No such file or directory: '../DATA/MIND-Small-0.5/train.txt'
就是提示下面这个

> 2023-05-16 07:05:30.443681: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-05-16 07:05:36.877800: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
| distributed init rank 0
Namespace(data_path='../DATA/MIND-Small', model_name='bert-base-uncased', train_data_path='../DATA/MIND-Small', epochs=5, batch_size=16, test_batch_size=100, lr=2e-05, wd=0.001, max_his=50, max_tokens=500, num_negs=4, max_his_len=450, num_conti1=3, num_conti2=3, device='cuda', world_size=1, model_save=True, log=True, save_dir='./model_save/2023-05-16-07-05-31', log_file='./log-Small-Few/bs16-Tbs100-lr2e-05-n33-ratioall-84717.txt', rank=0, gpu=0)
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Token indices sequence length is longer than the specified maximum sequence length for this model (577 > 512). Running this sequence through the model will result in indexing errors

这项工作确实很有趣，新颖，很想跑通看看

**Comment by Lotus-Blue** [comment]
是MIND-Small-0.5不是MIND-Small，还没仔细研究代码，打算先跑通再仔细学习这代码，很苦恼

**Comment by resistzzz** [comment]
> 是MIND-Small-0.5不是MIND-Small，还没仔细研究代码，打算先跑通再仔细学习这代码，很苦恼

MIND-Small-0.5是我用来跑后面的Few-shot learning用的数据集，如果用于复现表格中的实验，把数据集改为MIND-Small即可，处理好的MIND-Small我已经上传了Google Drive，在ReadMe中可以看到，只需要下载下来，改改数据存放路径，就可以跑通

**Comment by Lotus-Blue** [comment]
> 

感谢您的回复，我按照您的操作走了一遍，总是提示下面错误
![b898577a165cb0d390aeb820f8f6c25](https://github.com/resistzzz/Prompt4NR/assets/45590660/125cbb31-dbf5-49c6-a7aa-b893f69c70a0)
明明truncation=True，max_tokens设置了500，还会有这种错误。

**Comment by Lotus-Blue** [comment]
> > 是MIND-Small-0.5不是MIND-Small，还没仔细研究代码，打算先跑通再仔细学习这代码，很苦恼
> 
> MIND-Small-0.5是我用来跑后面的Few-shot learning用的数据集，如果用于复现表格中的实验，把数据集改为MIND-Small即可，处理好的MIND-Small我已经上传了Google Drive，在ReadMe中可以看到，只需要下载下来，改改数据存放路径，就可以跑通

不好意思打扰了，原来这个只是warning，我看到errors以为是报错了，等等跑成功看看。
另外我想问下这个txt文件用win11打开是乱码的，我也尝试换成其他编码格式，还是乱码
还是说只能用python的读写库进行预览呢

**Comment by Lotus-Blue** [comment]
> > 是MIND-Small-0.5不是MIND-Small，还没仔细研究代码，打算先跑通再仔细学习这代码，很苦恼
> 
> MIND-Small-0.5是我用来跑后面的Few-shot learning用的数据集，如果用于复现表格中的实验，把数据集改为MIND-Small即可，处理好的MIND-Small我已经上传了Google Drive，在ReadMe中可以看到，只需要下载下来，改改数据存放路径，就可以跑通

上面那两个都解决了，打扰您了，这两个其实都不是啥问题，自己某步搞错了

**Comment by duyanhedyh** [comment]
> > > 是MIND-Small-0.5不是MIND-Small，还没仔细研究代码，打算先跑通再仔细学习这代码，很苦恼
> > 
> > 
> > MIND-Small-0.5是我用来跑后面的Few-shot learning用的数据集，如果用于复现表格中的实验，把数据集改为MIND-Small即可，处理好的MIND-Small我已经上传了Google Drive，在ReadMe中可以看到，只需要下载下来，改改数据存放路径，就可以跑通
> 
> 上面那两个都解决了，打扰您了，这两个其实都不是啥问题，自己某步搞错了

您好，577>512需要解决吗？是致命的bug吗？另外，需要每一个sh运行多久？
