### ISSUE TITLE
实验数据疑问

### ISSUE THREAD

**Issue by HitAgain** [resistzzz/Prompt4NR#5]
首先非常感谢作者基于prompt对于新闻推荐的探索和代码展示，这里作者提到使用了mind-small数据集 但是这份数据是没有test，只有train和dev的。而作者预处理数据里却含有test，这里是对数据分片做了处理吗？那么论文中的模型效果到底是基于标准的mind-small dev还是作者自己构建的test呢？

**Comment by HitAgain** [comment]
> 首先非常感谢作者基于prompt对于新闻推荐的探索和代码展示，这里作者提到使用了mind-small数据集 但是这份数据是没有test，只有train和dev的。而作者预处理数据里却含有test，这里是对数据分片做了处理吗？那么论文中的模型效果到底是基于标准的mind-small dev还是作者自己构建的test呢？

查看了数据详情 大概了解了应该是 test.txt 等价于 dev set， val.txt 是从 train set 分出来的一部分~~

**Comment by resistzzz** [comment]
你好：

       非常感谢对我工作的关注，MIND公开的数据集test set是没有标签的，因为Test
set是当时用作比赛的，参赛者预测完之后上传，进行评测。因此没有标签。


 后续大家搞科研时，会采用dev作为test，然后从train里面划分一点出来做dev，这个操作你仔细一点，可以在好几篇论文里面的源码看到。我也采用了相同的做法。

      划分好的数据集你可以在我给的链接下载到

-Zizhuo

Weinan Gan ***@***.***> 于2023年10月18日周三 02:18写道：
